### PR TITLE
Clarify Enumerable#chunk - better grammar and examples.

### PR DESCRIPTION
**Pull request by danbernier**

### CODE REVIEW

**Comment by danbernier** [comment]
@zzak, where do we go from here? Thanks so much for your help with this!

cc @rbruchal.

**Comment by zzak** [comment]
@danbernier This is awesome, thank you! I'll try to review it sometime tomorrow.

**Comment by danbernier** [comment]
It's funny, as I was driving home last night, I came up with a good usage example for this: given a list of (say) commit-counts-by-developer-by-week, find the developer with the longest span of being the top commiter. (The example can generalize out to races, or bug reports, or whatever.) I may write it up for another pull request. :smile:

**Comment by zzak** [comment]
> It's funny, as I was driving home last night, I came up with a good usage example for this: given a list of (say) commit-counts-by-developer-by-week, find the developer with the longest span of being the top commiter.

Good idea! I'm really glad you guys decided to help out with the docs for your project night. I think this idea can apply to many projects, try asking other maintainers in the community if they'd like to partner up for some bug mashing.

**Comment by danbernier** [comment]
I was talking w/ one of the guys about that last night - bug smash redmine!
bugsmash rspec! etc etc etc. And if you pair a beginner w/ an old-hand, it
becomes a teaching tool, and (I think) can build enthusiasm in the
beginner: "look, we just helped out!"

On Thu, Feb 21, 2013 at 11:54 AM, Zachary Scott notifications@github.comwrote:

> It's funny, as I was driving home last night, I came up with a good usage
> example for this: given a list of (say) commit-counts-by-developer-by-week,
> find the developer with the longest span of being the top commiter.
> 
> Good idea! I'm really glad you guys decided to help out with the docs for
> your project night. I think this idea can apply to many projects, try
> asking other maintainers in the community if they'd like to partner up for
> some bug mashing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/documenting-ruby/ruby/pull/8#issuecomment-13899500.

## 

twitter @danbernier
http://wordcram.org | http://newhavenrb.org

**Comment by zzak** [comment]
@danbernier @rbruchal This patch landed in [r39370](https://github.com/ruby/ruby/commit/d2c218d), thanks for your contribution!

**Comment by danbernier** [comment]
Awesome, thanks!

On Thu, Feb 21, 2013 at 9:17 PM, Zachary Scott notifications@github.comwrote:

> @danbernier https://github.com/danbernier @rbruchalhttps://github.com/rbruchalThis patch landed in
> rd2c218d https://github.com/ruby/ruby/commit/d2c218d, thanks for your
> contribution!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/documenting-ruby/ruby/pull/8#issuecomment-13925130.

## 

twitter @danbernier
http://wordcram.org | http://newhavenrb.org

**Comment by rbruchal** [comment]
Very cool!

Sent from Alto - altomail.com

**Pull request closed without merging**
