### PR TITLE
Specify default of Logger.new shift_age option

### LINKED ISSUE #64: Specifying Logger.new shift_age option default
http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html#new-method

From only looking at the docs, it's not obvious what the default value is for shift_age, nor what value disables the option.  The only way to find out is to look at the code itself.

Can submit a PR with the following adjustment: https://github.com/documenting-ruby/ruby/compare/trunk...spacemunkay:specify-logger-shift-age-default

### PR DESCRIPTION
**Pull request by spacemunkay**
Closes #64.  Please see issue for details.

### CODE REVIEW

**Comment by davydovanton** [comment]
@spacemunkay thanks!
What do you think, may be we can add information about `shift_size` default value too?

**Comment by spacemunkay** [comment]
@davydovanton Good call!  updated

**Comment by spacemunkay** [comment]
@davydovanton Anything else I need to do?  This is my first time suggesting doc changes.  I'm assuming I should wait for this to get merged.  Let me know if there's more I need to do after that.

**Comment by spacemunkay** [comment]
@davydovanton checking in again.  Let me know what's next.

**Comment by davydovanton** [comment]
thanks for changes, I'll check this 👍

**Comment by spacemunkay** [comment]
Cool!

**Comment by spacemunkay** [comment]
@davydovanton gentle poke :)

**Comment by spacemunkay** [comment]
Okay, after not hearing back for a few months, I'm just going to attempt submitting a patch.  

No idea what I'm doing

**Comment by spacemunkay** [comment]
Submitted patch here: https://bugs.ruby-lang.org/issues/12803

**Comment by hsbt** [comment]
@spacemunkay Thank you for your suggestion. I merged your patch on ruby core repository.

**Comment by spacemunkay** [comment]
Awesome! Thanks!

I'm helping

**Comment by spacemunkay** [comment]
Resolved with https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/56420

**Pull request closed without merging**
