### PR TITLE
Clarify that Hash#invert will sometimes drop keys.

### PR DESCRIPTION
**Pull request by danbernier**
If multiple keys point to the same value, Hash#invert will drop them, but the docs don't mention this.

_Question:_ I'd love some feedback on the tone and clarity.

Thank you!

### CODE REVIEW

**Comment by zzak** [comment]
Interesting pointer, I try to avoid a lot of "buts" and other negatives. Simply because it assumes too much about the reader and can be easily confusing.

**Comment by danbernier** [comment]
Hrm - those are useful words for expressing a contradictory idea. But, like they say, "know your audience," right?

Do you think it'd be better to drop those ideas from the comment, or to re-word them so they're more direct, more positive?

**Comment by zzak** [comment]
I think its still useful information, but I would try to rephrase it as a feature of Hash#invert

**Comment by danbernier** [comment]
@zzak I took out the negative parts, so it just explains the behavior. Better, you think?

**Pull request closed without merging**
