### PR TITLE
improve IRB documentation

### PR DESCRIPTION
**Pull request by gnarargs**
PROMPT_I in prompt customization example can't be nil

### CODE REVIEW

**Comment by gnarargs** [comment]
When I use the example in my .irbrc, I get

```
|ruby-2.1.1@gschool| Hunters-MacBook-Pro in ~/ruby
± |trunk ✓| → irb
/Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:631:in `dup': can't dup NilClass (TypeError)
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:631:in `prompt'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:462:in `block in eval_input'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb/ruby-lex.rb:208:in `call'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb/ruby-lex.rb:208:in `prompt'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb/ruby-lex.rb:224:in `initialize_input'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:397:in `block in start'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:396:in `catch'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/irb.rb:396:in `start'
    from /Users/lemonofpink/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
```

Setting PROMPT_I to something other than nil fixes the issue.

**Comment by zzak** [comment]
@hgillane Thank you!

**Comment by gnarargs** [comment]
Cool thanks for the help! I'll try to send the next patch directly to Ruby. I appreciate what you are doing with this project!

**Comment by zzak** [comment]
@hgillane You can submit whichever way is easier for you, I have no preference <3

**Pull request closed without merging**
